// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOhcQLi1PAl7W6t4fZNnSMwMTr6PhC7ZE',
    appId: '1:505845794042:web:24cf3ea3ab9c906277b543',
    messagingSenderId: '505845794042',
    projectId: 'project1-9d81a',
    authDomain: 'project1-9d81a.firebaseapp.com',
    storageBucket: 'project1-9d81a.firebasestorage.app',
    measurementId: 'G-2THY9N5LH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_6eHqDCL1yfiKzJ_q118nMiuzni_0B2A',
    appId: '1:505845794042:android:d16332a07606751977b543',
    messagingSenderId: '505845794042',
    projectId: 'project1-9d81a',
    storageBucket: 'project1-9d81a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeIibeobuZltwL0_oFCHX7TvmS6B8HDdE',
    appId: '1:505845794042:ios:9e46336039e2f37c77b543',
    messagingSenderId: '505845794042',
    projectId: 'project1-9d81a',
    storageBucket: 'project1-9d81a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApuri1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeIibeobuZltwL0_oFCHX7TvmS6B8HDdE',
    appId: '1:505845794042:ios:9e46336039e2f37c77b543',
    messagingSenderId: '505845794042',
    projectId: 'project1-9d81a',
    storageBucket: 'project1-9d81a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApuri1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOhcQLi1PAl7W6t4fZNnSMwMTr6PhC7ZE',
    appId: '1:505845794042:web:0b118afe2b724ca377b543',
    messagingSenderId: '505845794042',
    projectId: 'project1-9d81a',
    authDomain: 'project1-9d81a.firebaseapp.com',
    storageBucket: 'project1-9d81a.firebasestorage.app',
    measurementId: 'G-JCZ8VQMYF6',
  );

}